apiVersion: v1
kind: ConfigMap
metadata: 
  name: app-config
  namespace: voting-app
data: 
  POSTGRES_DB: "votingdb"
  POSTGRES_USER: "voteuser"
  REDIS_HOST: "redis"
  POSTGRES_HOST: "postgres-service"